### PR TITLE
Fix edit command

### LINKED ISSUE #107: Update edit command
Edit command is now wrong in v1.3

### PR DESCRIPTION
**Pull request by thortol**
## Describe your changes
Modified edit command to include department, role and ced
## Issue ticket number and link
closes #107 
## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -52,6 +57,22 @@ public EditCommand parse(String args) throws ParseException {
             editPersonDescriptor.setAddress(ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).get()));
         }
 
+        if (argMultimap.getValue(PREFIX_DEPARTMENT).isPresent()) {
+            editPersonDescriptor.setDepartment(
+                    ParserUtil.parseDepartment(argMultimap.getValue(PREFIX_DEPARTMENT).get())
```
Comment (LimErnest) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:62]: Perhaps split these nested function calls into multiple lines to make it clearer?

File: src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java [hunk 2]
```diff
@@ -50,6 +53,18 @@ public void equals() {
         // different address -> returns false
         editedAmy = new EditPersonDescriptorBuilder(DESC_AMY).withAddress(VALID_ADDRESS_BOB).build();
         assertFalse(DESC_AMY.equals(editedAmy));
+
+        // different department -> returns false
+        editedAmy = new EditPersonDescriptorBuilder(DESC_AMY).withAddress(VALID_DEPARTMENT_BOB).build();
+        assertFalse(DESC_AMY.equals(editedAmy));
+
```
Comment (LimErnest) [inline src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java:60]: great use of comments!

**Review by LimErnest — APPROVED** [review]
LGTM! other than some minor stuff
