### PR TITLE
Fix a bug in sort date

### LINKED ISSUE #198: Sort puts potentials on top when desc is called

### PR DESCRIPTION
**Pull request by KiKuasaurus**
## Describe your changes
Add a new comparator to handle sorting by date in reverse to ensure that potential hires stay at the bottom.

## Issue ticket number and link
Closes #198

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PersonDateReverseComparatorTest.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+import static seedu.address.testutil.TypicalPersons.LILY;
+
+import java.util.ArrayList;
+
+import org.junit.jupiter.api.Test;
+
+public class PersonDateReverseComparatorTest {
+
+    @Test
+    public void sortsCorrectly() {
```
Comment (InfinityTwo) [inline src/test/java/seedu/address/model/person/PersonDateReverseComparatorTest.java]: Shouldn't the method name follow the test method naming convention?

**Review by InfinityTwo — APPROVED** [review]
LGTM for changes except for one comment
