### PR TITLE
Modify delete to support extra spaces bet params

### LINKED ISSUE #120: Delete command not supporting multiple spaces between parameters
example: `delete          ph            1` would not work

### PR DESCRIPTION
**Pull request by InfinityTwo**
## Describe your changes
Fixes the issue where spaces between parameters for delete would not work like `delete         ph      1`

## Issue ticket number and link
Closes #120 

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -14,28 +14,33 @@
  */
 public class DeleteCommandParser implements Parser<DeleteCommand> {
 
+    private boolean deleteParserCheck(String args, String commandType) throws ParseException {
+        if (args.startsWith(commandType)) {
```
Comment (thortol) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java:18]: You can consider replacing this with a guard clause. However since its not very nested its not a pressing issue.

File: src/test/java/seedu/address/logic/parser/AddressBookParserTest.java [hunk 2]
```diff
@@ -63,8 +63,10 @@ public void parseCommand_clear() throws Exception {
     @Test
     public void parseCommand_delete() throws Exception {
         DeleteCommand command = (DeleteCommand) parser.parseCommand(
-                DeleteCommand.COMMAND_WORD + " ph " + INDEX_FIRST_PERSON.getOneBased());
-        assertEquals(new DeletePotentialCommand(INDEX_FIRST_PERSON), command);
+                DeleteCommand.COMMAND_WORD + " "
+                        + DeleteEmployeeCommand.COMMAND_TYPE + " "
```
Comment (thortol) [inline src/test/java/seedu/address/logic/parser/AddressBookParserTest.java:67]: Great that you removed hardcoding!

**Review by thortol — APPROVED** [review]
LGTM
