### PR TITLE
Fix delete command error outputs

### LINKED ISSUE #185: delete e -1 and delete e 0 shld return invalid command error

### LINKED ISSUE #186: delete / delete a , shld return invalid format
image

image

### PR DESCRIPTION
**Pull request by InfinityTwo**
## Describe your changes
Modify delete error to be consistent with other commands as suggested by the two issues.
Add JavaDoc to deleteParserCheck

## Issue ticket number and link
Closes #185 and closes #186

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by LimErnest — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -14,6 +13,13 @@
  */
 public class DeleteCommandParser implements Parser<DeleteCommand> {
 
+    /**
+     * Checks if the command type is correct and if there is at least one space after command type.
```
Comment (KiKuasaurus) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java:17]: Should this not check if the user input is correct and not command type
