### PR TITLE
Fix Help UI broken dropdown hyperlink

### LINKED ISSUE #253: [PE-D][Tester D] Help Command dropdown UI
The dropdown is unable to navigate between the different commands except for clear and sort which are the first and last command

You may refer to a video i have recorded below

[https://drive.google.com/file/d/1MGA6HlDeCdkWwmCgsfAm8vChTU5U205R/view?usp=drive_link](url)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yongqqqq/ped#7

### PR DESCRIPTION
**Pull request by InfinityTwo**
## Describe your changes
Refer to title/linked issue

## Issue ticket number and link
Closes #253

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -466,7 +466,7 @@ private void scrollAndHighlightText(Text targetText) {
         }
 
         // type-casted to Hbox as every Text in helpWindow is wrapped by a Hbox as its parent
-        HBox box = (HBox) targetText.getParent().getParent().getParent();
+        HBox box = (HBox) targetText.getParent().getParent().getParent().getParent().getParent();
```
Comment (LimErnest) [inline src/main/java/seedu/address/ui/HelpWindow.java:471]: would be good to change the comment above to explain the chains of getParent() for easier understanding of the code and reason for typecasting

**Review by LimErnest — APPROVED** [review]

File: src/main/java/seedu/address/ui/HelpWindow.java (hunk 1 above)
Comment (InfinityTwo) [reply src/main/java/seedu/address/ui/HelpWindow.java:471]: Great catch! I have added comments on why there is a huge chain now.
